#!/bin/sh
#
# install.sh — auto-generated by build_package
# Edit stateCode below to advance the board lifecycle after install.
# All other sections are derived from the package contents.

set -e

# next board state after install (change if this package requires a specific state)
printf 'stateCode=%s\n' 0 > "$ACMS_BOARD_STATE"

exit 0
